// The cast-shadow lookup, in one place.
//
// Six shaders receive the shadow map -- terrain, road, unit, unit_detail, unit_pbr and
// water -- and until this file existed each carried its own hand-written copy of the
// filter. They were meant to be identical and mostly were, but "mostly" is the whole
// problem: a unit and the ground it stands on have to agree tap for tap about where a
// shadow edge falls, and a road is a decal on the terrain, so the two must agree exactly
// or the edge breaks where a shadow crosses onto tarmac. Six copies is six chances to
// widen a kernel in five of them.
//
// The build already knows about this file -- cmake/shaders.cmake globs *.hlsli and makes
// every shader depend on all of them, so editing the filter here rebuilds every receiver.
//
// What this does NOT own: the sampler and the constant registers. Every receiver binds
// the map on stage 5, but ShadowParams lands on a different register in each shader
// (c1 terrain/road, c8 unit, c16 unit_pbr), so the caller passes those in.

#ifndef RTS_SHADER_SHADOW_HLSLI
#define RTS_SHADER_SHADOW_HLSLI

// ---------------------------------------------------------------------------
// Storage format
// ---------------------------------------------------------------------------

// Depth is packed coarse-to-fine across RGB8 (see shadowdepth_ps.hlsl for why the channel
// weights are 255 and not 256). Everything that knows this lives in this one function, so
// moving the map to R32F or a moments format later is a change here and nowhere else.
//
// tex2Dlod, not tex2D, and deliberately so for every caller rather than only the ones that
// need it. unit_ps and unit_detail_ps call the filter inside dynamic flow control, where
// tex2D would want the implicit screen-space gradients a branch makes unavailable
// ("can't force branch with gradients on non-inputs"). An explicit level is not an
// approximation: the map is a single-level render target sampled with point filtering, so
// level 0 is the only level there has ever been. Using it everywhere means the filter has
// one form and any receiver may branch around it without the filter caring.
float shadowSampleDepth(sampler2D shadowMap, float2 uv)
{
    float4 rgba = tex2Dlod(shadowMap, float4(uv, 0.0, 0.0));
    return dot(rgba.xyz, float3(1.0, 1.0 / 255.0, 1.0 / (255.0 * 255.0)));
}

// ---------------------------------------------------------------------------
// Sample pattern
// ---------------------------------------------------------------------------

// Poisson-disk sample sets, generated by best-candidate sampling followed by Lloyd
// relaxation in the unit disk, then scaled so the outermost sample sits on the unit
// circle. The 16-tap set has a minimum separation of 0.464 of the kernel radius and the
// 8-tap set 0.804, both close to the theoretical best for that count -- which is what
// keeps a sparse kernel from clumping and leaving holes the shadow edge falls through.
//
// Sixteen taps is not an increase in fetch *count*. The filter this replaced was a 3-texel
// box that also cost sixteen fetches; the taps have simply been spread over a radius that
// can reach six texels instead of one and a half.
//
// It is not free even so, and the reason is locality rather than count: sixteen taps inside
// a 4x4 texel box mostly hit the same cache lines, and the same sixteen spread over a 12x12
// disk do not. Terrain is the one to watch -- it is full-screen and it is the surface most
// shadows land on. Worth measuring rather than assuming, and worth remembering that the
// replay harness's 30 Hz cap makes wall-clock timing useless for ranking this.
static const float2 POISSON_16[16] = {
    float2(-0.374526, -0.833571),
    float2( 0.159100,  0.907824),
    float2(-0.774040,  0.560997),
    float2( 0.950166, -0.311745),
    float2( 0.095356, -0.313390),
    float2( 0.640793,  0.717949),
    float2(-0.333629,  0.877176),
    float2(-0.809816, -0.561398),
    float2( 0.577181, -0.715537),
    float2(-0.436015, -0.218353),
    float2( 0.531379, -0.085042),
    float2(-0.324788,  0.232625),
    float2( 0.212296,  0.315334),
    float2( 0.894443,  0.268246),
    float2(-0.959210,  0.021282),
    float2( 0.107770, -0.915608)
};

// The cheap set, for water. Not a prefix of the sixteen -- a prefix of a Poisson set is
// not itself Poisson, it is the first few of a denser set and clumps accordingly -- so
// this is its own relaxed set of eight.
static const float2 POISSON_8[8] = {
    float2(-0.967533,  0.239772),
    float2( 0.928131,  0.100633),
    float2( 0.510183,  0.838753),
    float2(-0.089422, -0.972875),
    float2(-0.388617,  0.916548),
    float2(-0.068096, -0.019632),
    float2(-0.801209, -0.598384),
    float2( 0.671139, -0.692316)
};

// Per-pixel rotation of the sample disk.
//
// Sixteen taps spread over a radius of several texels is a sparse kernel, and a *fixed*
// sparse kernel does not blur an edge so much as replace it with sixteen banded steps in
// the same place on every pixel. Rotating the disk by a different angle per pixel trades
// that banding for noise, which at this camera reads as a faint grain instead of as rings.
//
// The angle comes from the shadow-map texel the pixel falls in, not from its screen
// position. That is the important part: a screen-locked pattern crawls across the ground
// whenever the camera moves, which is precisely the artefact the sun frustum is snapped to
// whole texels to avoid (see W3DView). World-locked noise sits still. It repatterns when
// the fitted extent changes, but that is quantised to 64-unit steps, so it happens at zoom
// steps rather than continuously.
//
// The hash is the 2D Weyl/R2 low-discrepancy sequence -- frac of a dot with two irrational
// constants -- rather than the usual frac(sin(dot(...))*43758.5). No trig, no dependence
// on how a particular driver evaluates sin far from the origin, and the fracs are taken
// per-component so the products stay small enough to keep their low bits.
float2 shadowRotation(float2 uv, float texel)
{
    float2 cell = floor(uv / texel);
    float2 r    = frac(cell * float2(0.7548776662, 0.5698402909));
    float  a    = frac(r.x + r.y) * 6.2831853;
    return float2(cos(a), sin(a));
}

// ---------------------------------------------------------------------------
// Receiver-plane depth bias
// ---------------------------------------------------------------------------

// The thing that makes a wide kernel possible at all.
//
// A tap several texels away compares *this* pixel's depth against the map at a point the
// surface has since sloped away from. On anything not perpendicular to the sun that error
// grows with the kernel radius, so a filter wide enough to soften an edge is also wide
// enough to make every sunlit slope shadow itself. Answering that with a bigger constant
// bias is the trap: bias is a depth licence granted everywhere, and enough of it to cover
// the outermost tap on a steep slope is far more than enough to lift a small caster clean
// out of its own shadow -- the failure the old 0.0025 blanket bias had, and the reason the
// mesh path moved to a normal offset instead.
//
// Instead, work out how the receiver's own depth changes per unit of shadow-map UV, and
// ask each tap for the depth the surface would have *there*. Then the comparison is
// plane-against-map rather than point-against-map, the slope term cancels, and what is
// left for a constant bias is only numerical slack -- which is what lets the constants in
// W3DView come down rather than up when the kernel widens.
//
// Must be called in unbranched code: ddx/ddy need the screen-space neighbours, which
// dynamic flow control makes unavailable. Receivers that branch around the filter compute
// this before the branch (it is a dozen ALU against sixteen fetches, so the branch still
// pays for itself many times over).
float2 shadowReceiverGradient(float2 uv, float z)
{
    float2 dudx = ddx(uv), dudy = ddy(uv);
    float  dzdx = ddx(z),  dzdy = ddy(z);

    // Solving [dzdx; dzdy] = M * [dz/du; dz/dv] for the gradient, where M holds the two
    // screen-space derivatives of uv as its rows.
    float det = dudx.x * dudy.y - dudx.y * dudy.x;

    // A degenerate Jacobian means there is no plane to fit: a polygon seen edge-on from
    // the sun, or a pixel quad straddling a silhouette where the neighbours belong to
    // different surfaces. Ask for no correction rather than dividing by ~0 and getting a
    // gradient that sends every outer tap to a nonsense depth.
    if (abs(det) < 1e-12)
        return float2(0.0, 0.0);

    float inv = 1.0 / det;
    return float2(( dudy.y * dzdx - dudx.y * dzdy) * inv,
                  (-dudy.x * dzdx + dudx.x * dzdy) * inv);
}

// How far the plane correction may move a tap's reference depth, as a multiple of the
// constant bias *per texel of kernel radius*. The gradient is fitted from a 2x2 pixel quad,
// so at a silhouette it can still come back steep even after the determinant guard -- one
// pixel of the quad on a roof and three on the ground behind it fits a plane through
// neither. Bounding the correction keeps that a local softening rather than a hole punched
// through the shadow.
//
// It has to scale with the radius, not be a bare multiple of the bias: the correction a
// legitimate slope needs is proportional to how far the outermost tap reaches, so a fixed
// multiple would start clipping real slopes as soon as the kernel widened -- which would
// quietly put the acne back that the plane fit exists to remove.
#define SHADOW_PLANE_CLAMP  8.0

// ---------------------------------------------------------------------------
// The filter
// ---------------------------------------------------------------------------

// One tap: offset within the kernel, plane-corrected compare, and the out-of-map guard.
float shadowTap(sampler2D shadowMap, float2 uv, float2 offsetUv,
                float zRef, float2 dzduv, float bias, float planeLimit)
{
    float2 t = uv + offsetUv;

    // The depth this same surface would have at the tap, not the depth it has here.
    float plane = clamp(dot(dzduv, offsetUv), -planeLimit, planeLimit);
    float lit = ((zRef + plane) - bias > shadowSampleDepth(shadowMap, t)) ? 0.0 : 1.0;

    // Taps that leave the map are the wide kernel's own problem: stage 5 is CLAMP, so an
    // out-of-range tap silently reads the border texel, which holds some unrelated
    // surface's depth and would stamp a false shadow along the map edge. The old kernel
    // tested the centre once and was narrow enough for that to cover it; at several texels
    // of radius the centre can be inside while half the disk is not. Outside the sun
    // frustum nothing is shadowed, so those taps count as lit.
    float2 d = abs(t - 0.5);
    return (max(d.x, d.y) > 0.5) ? 1.0 : lit;
}

// Sixteen taps. The kernel radius arrives in texels from the CPU (ShadowParams.w) rather
// than being baked, because it is sized in *world* units up there -- a radius fixed in
// texels would make the penumbra grow and shrink with the zoom, since the sun frustum is
// fitted to the camera and a texel is worth a different amount of ground at each zoom.
//
// zRef is the pixel's own depth in sun-clip units; bias is what is left for numerical
// slack once the normal offset (meshes) or the slope allowance (terrain) has done its job.
float shadowFilter16(sampler2D shadowMap, float2 uv, float zRef,
                     float texel, float radiusTexels, float2 dzduv, float bias)
{
    float2 rot   = shadowRotation(uv, texel);
    float  scale = texel * radiusTexels;
    float  limit = bias * SHADOW_PLANE_CLAMP * max(radiusTexels, 1.0);

    float lit = 0.0;
    [unroll] for (int i = 0; i < 16; ++i)
    {
        float2 p = POISSON_16[i];
        float2 o = float2(p.x * rot.x - p.y * rot.y,
                          p.x * rot.y + p.y * rot.x) * scale;
        lit += shadowTap(shadowMap, uv, o, zRef, dzduv, bias, limit);
    }
    return lit * (1.0 / 16.0);
}

// Eight taps, for water. Half the cost, and the surface it shades is large, smooth and
// already broken up by its own normals -- there is nothing on the water sharp enough to
// show the difference. It also only gates a specular highlight and a partial darkening.
float shadowFilter8(sampler2D shadowMap, float2 uv, float zRef,
                    float texel, float radiusTexels, float2 dzduv, float bias)
{
    float2 rot   = shadowRotation(uv, texel);
    float  scale = texel * radiusTexels;
    float  limit = bias * SHADOW_PLANE_CLAMP * max(radiusTexels, 1.0);

    float lit = 0.0;
    [unroll] for (int i = 0; i < 8; ++i)
    {
        float2 p = POISSON_8[i];
        float2 o = float2(p.x * rot.x - p.y * rot.y,
                          p.x * rot.y + p.y * rot.x) * scale;
        lit += shadowTap(shadowMap, uv, o, zRef, dzduv, bias, limit);
    }
    return lit * (1.0 / 8.0);
}

// ---------------------------------------------------------------------------
// Projection
// ---------------------------------------------------------------------------

// Sun clip space -> the NDC the filter wants. Guarded: a degenerate w yields inf, then
// NaN, and NaN survives every operation after it -- the pixel is simply gone.
float3 shadowNdc(float4 lightPos)
{
    return lightPos.xyz / max(abs(lightPos.w), 1e-6);
}

// NDC -> shadow-map UV. The Y flip is the texture's, not the projection's.
float2 shadowUv(float3 ndc)
{
    return ndc.xy * float2(0.5, -0.5) + 0.5;
}

#endif  // RTS_SHADER_SHADOW_HLSLI
